export const DictionaryLiveness = {
  hintMoveFaceFrontOfCameraText: "Posicione seu rosto em frente à câmera.",
  hintTooManyFacesText: "Muitos rostos detectados.",
  hintFaceDetectedText: "Rosto detectado.",
  hintCanNotIdentifyText: "Não foi possível identificar o rosto.",
  hintTooCloseText: "Você está muito perto da câmera.",
  hintTooFarText: "Você está muito longe da câmera.",
  hintConnectingText: "Conectando...",
  hintVerifyingText: "Verificando...",
  hintCheckCompleteText: "Verificação completa.",
  hintIlluminationTooBrightText: "A iluminação está muito forte.",
  hintIlluminationTooDarkText: "A iluminação está muito fraca.",
  hintIlluminationNormalText: "A iluminação está normal.",
  hintHoldFaceForFreshnessText: "Mantenha o rosto parado para análise.",
  hintCenterFaceText: "Centralize seu rosto.",
  hintCenterFaceInstructionText: "Por favor, centralize seu rosto na tela.",
  hintFaceOffCenterText: "O rosto está fora do centro.",
  hintMatchIndicatorText: "Indicador de correspondência ativo.",
  cameraMinSpecificationsHeadingText: "Especificações mínimas da câmera",
  cameraMinSpecificationsMessageText:
    "A câmera não atende às especificações mínimas.",
  cameraNotFoundHeadingText: "Câmera não encontrada",
  cameraNotFoundMessageText: "Nenhuma câmera foi detectada.",
  retryCameraPermissionsText: "Tentar novamente as permissões da câmera",
  waitingCameraPermissionText: "Aguardando permissão da câmera",
  a11yVideoLabelText: "Etiqueta de vídeo para acessibilidade",
  goodFitCaptionText: "Posicionamento adequado",
  goodFitAltText: "Descrição alternativa para posicionamento adequado",
  photosensitivityWarningBodyText: "Aviso para pessoas com fotosensibilidade",
  photosensitivityWarningHeadingText: "Aviso de Fotosensibilidade",
  photosensitivityWarningInfoText: "Informações sobre fotosensibilidade",
  photosensitivityWarningLabelText: "Etiqueta de aviso de fotosensibilidade",
  startScreenBeginCheckText: "Iniciar verificação",
  tooFarCaptionText: "Demasiadamente distante",
  tooFarAltText: "Descrição alternativa para estar muito distante",
  recordingIndicatorText: "Indicador de gravação",
  cancelLivenessCheckText: "Cancelar verificação de vivacidade",
  errorLabelText: "Erro detectado",
  connectionTimeoutHeaderText: "Tempo de conexão esgotado",
  connectionTimeoutMessageText: "Não foi possível conectar ao servidor.",
  timeoutHeaderText: "Tempo Esgotado",
  timeoutMessageText: "A operação excedeu o tempo limite.",
  faceDistanceHeaderText: "Distância do Rosto Inadequada",
  faceDistanceMessageText:
    "Ajuste a distância do seu rosto em relação à câmera.",
  multipleFacesHeaderText: "Múltiplos Rostos Detectados",
  multipleFacesMessageText:
    "Por favor, assegure que apenas um rosto esteja visível.",
  clientHeaderText: "Erro do Cliente",
  clientMessageText: "Erro de processamento no lado do cliente.",
  serverHeaderText: "Erro do Servidor",
  serverMessageText: "Erro de processamento no lado do servidor.",
  landscapeHeaderText: "Orientação Paisagem",
  landscapeMessageText:
    "Por favor, ajuste a orientação do dispositivo para paisagem.",
  portraitMessageText:
    "Por favor, ajuste a orientação do dispositivo para retrato.",
  tryAgainText: "Tente novamente",
};
